### ISSUE TITLE
What's this??

### ISSUE THREAD

**Issue by josephting** [jerry54604/my-profile#1]
:open_mouth: what is this??
pro typescript :open_mouth:

**Comment by jerry54604** [comment]
my profile lol

**Comment by josephting** [comment]
I only see **Loading** and **app works!**

**Comment by jerry54604** [comment]
thats what it suppose to show, show i'm a noob 😢

**Comment by josephting** [comment]
walao totally pro
write so much pro code just to do that one thing :+1:

**Comment by jerry54604** [comment]
lol, i didnt write so much, just use ng new and ng serve XD

**Comment by josephting** [comment]
lol still pro 😆

**Comment by josephting** [comment]
https://github.com/jerry54604/jinyong-legend-py

WHAT IS THIS!?!?!? :open_mouth: :open_mouth: :open_mouth: 
Game???? :open_mouth: :open_mouth: :open_mouth: :open_mouth:

**Comment by jerry54604** [comment]
ya, a game
Proseph like that also know 😮

**Comment by josephting** [comment]
lol pro game developer
Text based or what? :open_mouth:

**Comment by jerry54604** [comment]
2d sprite based?
just forking ppl's code where got pro 😢

**Comment by josephting** [comment]
lol fork means want to make changes to it.
Planning to make changes to it means know what this is. :open_mouth: 

Wow got sound and graphics also LOL
IMBA game. Thought can play at work. :disappointed:

**Comment by jerry54604** [comment]
lol
still trying to make sense of what it is, im too noob 😢

**Comment by josephting** [comment]
I totally don't know what this is

**Comment by jerry54604** [comment]
at least you know it is game 😮

**Comment by josephting** [comment]
lol because of the title
